apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - port: 3012
    protocol: TCP
    name: nodejs
  selector:
    app: {{ .Values.appName }}
    tier: frontend
  type: LoadBalancer