

appName: node-cat

port: 3012

namespace: default

configmap:
  name: myhelmapp-configmap-v1
  data:
    CUSTOM_HEADER: 'This app was deployed with helm!'

image:
  name: fandilladp/node-cat-app
  tag: latest

dbConfig:
  host: "127.0.0.1"
  port: "5432"
  database: "postgres"

dbCredentials:
  user: "postgres"
  password: "mypassword"


autoscaling:
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30
