kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  host: {{ .Values.dbConfig.host | quote }}
  port: {{ .Values.dbConfig.port | quote }}
  database: {{ .Values.dbConfig.database | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
stringData:
  user: {{ .Values.dbCredentials.user | quote }}
  password: {{ .Values.dbCredentials.password | quote }}