appName: postgresql

port: 5432

namespace: default

configmap:
  name: myhelmapp-configmap-v1
  data:
    CUSTOM_HEADER: 'This app was deployed with helm!'
  username: postgres
  password: postgres

image:
  name: postgres/node-cat-app
  tag: latest

autoscaling:
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30
